В JavaScript обработка ошибок в цепочке промисов осуществляется с помощью метода .catch(), который служит 
для перехвата ошибок, возникших как в самом промисе, так и в последующих методах .then(). Давайте рассмотрим на примере, как это работает.
Основы обработки ошибок в промисах
Если ошибка возникает в любом месте цепочки, вы можете поймать ее с помощью одного .catch() в конце цепочки.

Важно
1. Если ошибка произойдет в firstFunction(), она будет перехвачена в самом конце с использованием .catch().
2. Если ошибка произойдет в secondFunction(), она также будет перехвачена тем же .catch(), поскольку все вызовы промисов находятся в цепочке.